[project]
name = 'yebocoin'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.yebocoin]
path = 'contracts/yebocoin.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
